// Code generated by ent, DO NOT EDIT.

package event

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the event type in the database.
	Label = "event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClassUID holds the string denoting the class_uid field in the database.
	FieldClassUID = "class_uid"
	// FieldCategoryUID holds the string denoting the category_uid field in the database.
	FieldCategoryUID = "category_uid"
	// FieldActivityID holds the string denoting the activity_id field in the database.
	FieldActivityID = "activity_id"
	// FieldTypeUID holds the string denoting the type_uid field in the database.
	FieldTypeUID = "type_uid"
	// FieldSeverityID holds the string denoting the severity_id field in the database.
	FieldSeverityID = "severity_id"
	// FieldStatusID holds the string denoting the status_id field in the database.
	FieldStatusID = "status_id"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// FieldIngestedAt holds the string denoting the ingested_at field in the database.
	FieldIngestedAt = "ingested_at"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSchemaVersion holds the string denoting the schema_version field in the database.
	FieldSchemaVersion = "schema_version"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldRawData holds the string denoting the raw_data field in the database.
	FieldRawData = "raw_data"
	// Table holds the table name of the event in the database.
	Table = "events"
)

// Columns holds all SQL columns for event fields.
var Columns = []string{
	FieldID,
	FieldClassUID,
	FieldCategoryUID,
	FieldActivityID,
	FieldTypeUID,
	FieldSeverityID,
	FieldStatusID,
	FieldTime,
	FieldIngestedAt,
	FieldSource,
	FieldSchemaVersion,
	FieldPayload,
	FieldRawData,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ClassUIDValidator is a validator for the "class_uid" field. It is called by the builders before save.
	ClassUIDValidator func(int) error
	// CategoryUIDValidator is a validator for the "category_uid" field. It is called by the builders before save.
	CategoryUIDValidator func(int) error
	// ActivityIDValidator is a validator for the "activity_id" field. It is called by the builders before save.
	ActivityIDValidator func(int) error
	// TypeUIDValidator is a validator for the "type_uid" field. It is called by the builders before save.
	TypeUIDValidator func(int) error
	// SeverityIDValidator is a validator for the "severity_id" field. It is called by the builders before save.
	SeverityIDValidator func(int) error
	// StatusIDValidator is a validator for the "status_id" field. It is called by the builders before save.
	StatusIDValidator func(int) error
	// DefaultIngestedAt holds the default value on creation for the "ingested_at" field.
	DefaultIngestedAt func() time.Time
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultSchemaVersion holds the default value on creation for the "schema_version" field.
	DefaultSchemaVersion string
)

// OrderOption defines the ordering options for the Event queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClassUID orders the results by the class_uid field.
func ByClassUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClassUID, opts...).ToFunc()
}

// ByCategoryUID orders the results by the category_uid field.
func ByCategoryUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryUID, opts...).ToFunc()
}

// ByActivityID orders the results by the activity_id field.
func ByActivityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityID, opts...).ToFunc()
}

// ByTypeUID orders the results by the type_uid field.
func ByTypeUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTypeUID, opts...).ToFunc()
}

// BySeverityID orders the results by the severity_id field.
func BySeverityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverityID, opts...).ToFunc()
}

// ByStatusID orders the results by the status_id field.
func ByStatusID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusID, opts...).ToFunc()
}

// ByTime orders the results by the time field.
func ByTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTime, opts...).ToFunc()
}

// ByIngestedAt orders the results by the ingested_at field.
func ByIngestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIngestedAt, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySchemaVersion orders the results by the schema_version field.
func BySchemaVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchemaVersion, opts...).ToFunc()
}

// ByRawData orders the results by the raw_data field.
func ByRawData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawData, opts...).ToFunc()
}
