// Code generated by ent, DO NOT EDIT.

package event

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/ocsf-lake/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldID, id))
}

// ClassUID applies equality check predicate on the "class_uid" field. It's identical to ClassUIDEQ.
func ClassUID(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldClassUID, v))
}

// CategoryUID applies equality check predicate on the "category_uid" field. It's identical to CategoryUIDEQ.
func CategoryUID(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCategoryUID, v))
}

// ActivityID applies equality check predicate on the "activity_id" field. It's identical to ActivityIDEQ.
func ActivityID(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldActivityID, v))
}

// TypeUID applies equality check predicate on the "type_uid" field. It's identical to TypeUIDEQ.
func TypeUID(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldTypeUID, v))
}

// SeverityID applies equality check predicate on the "severity_id" field. It's identical to SeverityIDEQ.
func SeverityID(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldSeverityID, v))
}

// StatusID applies equality check predicate on the "status_id" field. It's identical to StatusIDEQ.
func StatusID(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldStatusID, v))
}

// Time applies equality check predicate on the "time" field. It's identical to TimeEQ.
func Time(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldTime, v))
}

// IngestedAt applies equality check predicate on the "ingested_at" field. It's identical to IngestedAtEQ.
func IngestedAt(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldIngestedAt, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldSource, v))
}

// SchemaVersion applies equality check predicate on the "schema_version" field. It's identical to SchemaVersionEQ.
func SchemaVersion(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldSchemaVersion, v))
}

// RawData applies equality check predicate on the "raw_data" field. It's identical to RawDataEQ.
func RawData(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRawData, v))
}

// ClassUIDEQ applies the EQ predicate on the "class_uid" field.
func ClassUIDEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldClassUID, v))
}

// ClassUIDNEQ applies the NEQ predicate on the "class_uid" field.
func ClassUIDNEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldClassUID, v))
}

// ClassUIDIn applies the In predicate on the "class_uid" field.
func ClassUIDIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldClassUID, vs...))
}

// ClassUIDNotIn applies the NotIn predicate on the "class_uid" field.
func ClassUIDNotIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldClassUID, vs...))
}

// ClassUIDGT applies the GT predicate on the "class_uid" field.
func ClassUIDGT(v int) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldClassUID, v))
}

// ClassUIDGTE applies the GTE predicate on the "class_uid" field.
func ClassUIDGTE(v int) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldClassUID, v))
}

// ClassUIDLT applies the LT predicate on the "class_uid" field.
func ClassUIDLT(v int) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldClassUID, v))
}

// ClassUIDLTE applies the LTE predicate on the "class_uid" field.
func ClassUIDLTE(v int) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldClassUID, v))
}

// CategoryUIDEQ applies the EQ predicate on the "category_uid" field.
func CategoryUIDEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCategoryUID, v))
}

// CategoryUIDNEQ applies the NEQ predicate on the "category_uid" field.
func CategoryUIDNEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCategoryUID, v))
}

// CategoryUIDIn applies the In predicate on the "category_uid" field.
func CategoryUIDIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCategoryUID, vs...))
}

// CategoryUIDNotIn applies the NotIn predicate on the "category_uid" field.
func CategoryUIDNotIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCategoryUID, vs...))
}

// CategoryUIDGT applies the GT predicate on the "category_uid" field.
func CategoryUIDGT(v int) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCategoryUID, v))
}

// CategoryUIDGTE applies the GTE predicate on the "category_uid" field.
func CategoryUIDGTE(v int) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCategoryUID, v))
}

// CategoryUIDLT applies the LT predicate on the "category_uid" field.
func CategoryUIDLT(v int) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCategoryUID, v))
}

// CategoryUIDLTE applies the LTE predicate on the "category_uid" field.
func CategoryUIDLTE(v int) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCategoryUID, v))
}

// ActivityIDEQ applies the EQ predicate on the "activity_id" field.
func ActivityIDEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldActivityID, v))
}

// ActivityIDNEQ applies the NEQ predicate on the "activity_id" field.
func ActivityIDNEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldActivityID, v))
}

// ActivityIDIn applies the In predicate on the "activity_id" field.
func ActivityIDIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldActivityID, vs...))
}

// ActivityIDNotIn applies the NotIn predicate on the "activity_id" field.
func ActivityIDNotIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldActivityID, vs...))
}

// ActivityIDGT applies the GT predicate on the "activity_id" field.
func ActivityIDGT(v int) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldActivityID, v))
}

// ActivityIDGTE applies the GTE predicate on the "activity_id" field.
func ActivityIDGTE(v int) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldActivityID, v))
}

// ActivityIDLT applies the LT predicate on the "activity_id" field.
func ActivityIDLT(v int) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldActivityID, v))
}

// ActivityIDLTE applies the LTE predicate on the "activity_id" field.
func ActivityIDLTE(v int) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldActivityID, v))
}

// TypeUIDEQ applies the EQ predicate on the "type_uid" field.
func TypeUIDEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldTypeUID, v))
}

// TypeUIDNEQ applies the NEQ predicate on the "type_uid" field.
func TypeUIDNEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldTypeUID, v))
}

// TypeUIDIn applies the In predicate on the "type_uid" field.
func TypeUIDIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldTypeUID, vs...))
}

// TypeUIDNotIn applies the NotIn predicate on the "type_uid" field.
func TypeUIDNotIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldTypeUID, vs...))
}

// TypeUIDGT applies the GT predicate on the "type_uid" field.
func TypeUIDGT(v int) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldTypeUID, v))
}

// TypeUIDGTE applies the GTE predicate on the "type_uid" field.
func TypeUIDGTE(v int) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldTypeUID, v))
}

// TypeUIDLT applies the LT predicate on the "type_uid" field.
func TypeUIDLT(v int) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldTypeUID, v))
}

// TypeUIDLTE applies the LTE predicate on the "type_uid" field.
func TypeUIDLTE(v int) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldTypeUID, v))
}

// SeverityIDEQ applies the EQ predicate on the "severity_id" field.
func SeverityIDEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldSeverityID, v))
}

// SeverityIDNEQ applies the NEQ predicate on the "severity_id" field.
func SeverityIDNEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldSeverityID, v))
}

// SeverityIDIn applies the In predicate on the "severity_id" field.
func SeverityIDIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldSeverityID, vs...))
}

// SeverityIDNotIn applies the NotIn predicate on the "severity_id" field.
func SeverityIDNotIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldSeverityID, vs...))
}

// SeverityIDGT applies the GT predicate on the "severity_id" field.
func SeverityIDGT(v int) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldSeverityID, v))
}

// SeverityIDGTE applies the GTE predicate on the "severity_id" field.
func SeverityIDGTE(v int) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldSeverityID, v))
}

// SeverityIDLT applies the LT predicate on the "severity_id" field.
func SeverityIDLT(v int) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldSeverityID, v))
}

// SeverityIDLTE applies the LTE predicate on the "severity_id" field.
func SeverityIDLTE(v int) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldSeverityID, v))
}

// SeverityIDIsNil applies the IsNil predicate on the "severity_id" field.
func SeverityIDIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldSeverityID))
}

// SeverityIDNotNil applies the NotNil predicate on the "severity_id" field.
func SeverityIDNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldSeverityID))
}

// StatusIDEQ applies the EQ predicate on the "status_id" field.
func StatusIDEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldStatusID, v))
}

// StatusIDNEQ applies the NEQ predicate on the "status_id" field.
func StatusIDNEQ(v int) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldStatusID, v))
}

// StatusIDIn applies the In predicate on the "status_id" field.
func StatusIDIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldStatusID, vs...))
}

// StatusIDNotIn applies the NotIn predicate on the "status_id" field.
func StatusIDNotIn(vs ...int) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldStatusID, vs...))
}

// StatusIDGT applies the GT predicate on the "status_id" field.
func StatusIDGT(v int) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldStatusID, v))
}

// StatusIDGTE applies the GTE predicate on the "status_id" field.
func StatusIDGTE(v int) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldStatusID, v))
}

// StatusIDLT applies the LT predicate on the "status_id" field.
func StatusIDLT(v int) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldStatusID, v))
}

// StatusIDLTE applies the LTE predicate on the "status_id" field.
func StatusIDLTE(v int) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldStatusID, v))
}

// StatusIDIsNil applies the IsNil predicate on the "status_id" field.
func StatusIDIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldStatusID))
}

// StatusIDNotNil applies the NotNil predicate on the "status_id" field.
func StatusIDNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldStatusID))
}

// TimeEQ applies the EQ predicate on the "time" field.
func TimeEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldTime, v))
}

// TimeNEQ applies the NEQ predicate on the "time" field.
func TimeNEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldTime, v))
}

// TimeIn applies the In predicate on the "time" field.
func TimeIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldTime, vs...))
}

// TimeNotIn applies the NotIn predicate on the "time" field.
func TimeNotIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldTime, vs...))
}

// TimeGT applies the GT predicate on the "time" field.
func TimeGT(v int64) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldTime, v))
}

// TimeGTE applies the GTE predicate on the "time" field.
func TimeGTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldTime, v))
}

// TimeLT applies the LT predicate on the "time" field.
func TimeLT(v int64) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldTime, v))
}

// TimeLTE applies the LTE predicate on the "time" field.
func TimeLTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldTime, v))
}

// IngestedAtEQ applies the EQ predicate on the "ingested_at" field.
func IngestedAtEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldIngestedAt, v))
}

// IngestedAtNEQ applies the NEQ predicate on the "ingested_at" field.
func IngestedAtNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldIngestedAt, v))
}

// IngestedAtIn applies the In predicate on the "ingested_at" field.
func IngestedAtIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldIngestedAt, vs...))
}

// IngestedAtNotIn applies the NotIn predicate on the "ingested_at" field.
func IngestedAtNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldIngestedAt, vs...))
}

// IngestedAtGT applies the GT predicate on the "ingested_at" field.
func IngestedAtGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldIngestedAt, v))
}

// IngestedAtGTE applies the GTE predicate on the "ingested_at" field.
func IngestedAtGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldIngestedAt, v))
}

// IngestedAtLT applies the LT predicate on the "ingested_at" field.
func IngestedAtLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldIngestedAt, v))
}

// IngestedAtLTE applies the LTE predicate on the "ingested_at" field.
func IngestedAtLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldIngestedAt, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldSource, v))
}

// SchemaVersionEQ applies the EQ predicate on the "schema_version" field.
func SchemaVersionEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldSchemaVersion, v))
}

// SchemaVersionNEQ applies the NEQ predicate on the "schema_version" field.
func SchemaVersionNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldSchemaVersion, v))
}

// SchemaVersionIn applies the In predicate on the "schema_version" field.
func SchemaVersionIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldSchemaVersion, vs...))
}

// SchemaVersionNotIn applies the NotIn predicate on the "schema_version" field.
func SchemaVersionNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldSchemaVersion, vs...))
}

// SchemaVersionGT applies the GT predicate on the "schema_version" field.
func SchemaVersionGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldSchemaVersion, v))
}

// SchemaVersionGTE applies the GTE predicate on the "schema_version" field.
func SchemaVersionGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldSchemaVersion, v))
}

// SchemaVersionLT applies the LT predicate on the "schema_version" field.
func SchemaVersionLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldSchemaVersion, v))
}

// SchemaVersionLTE applies the LTE predicate on the "schema_version" field.
func SchemaVersionLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldSchemaVersion, v))
}

// SchemaVersionContains applies the Contains predicate on the "schema_version" field.
func SchemaVersionContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldSchemaVersion, v))
}

// SchemaVersionHasPrefix applies the HasPrefix predicate on the "schema_version" field.
func SchemaVersionHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldSchemaVersion, v))
}

// SchemaVersionHasSuffix applies the HasSuffix predicate on the "schema_version" field.
func SchemaVersionHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldSchemaVersion, v))
}

// SchemaVersionEqualFold applies the EqualFold predicate on the "schema_version" field.
func SchemaVersionEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldSchemaVersion, v))
}

// SchemaVersionContainsFold applies the ContainsFold predicate on the "schema_version" field.
func SchemaVersionContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldSchemaVersion, v))
}

// RawDataEQ applies the EQ predicate on the "raw_data" field.
func RawDataEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRawData, v))
}

// RawDataNEQ applies the NEQ predicate on the "raw_data" field.
func RawDataNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldRawData, v))
}

// RawDataIn applies the In predicate on the "raw_data" field.
func RawDataIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldRawData, vs...))
}

// RawDataNotIn applies the NotIn predicate on the "raw_data" field.
func RawDataNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldRawData, vs...))
}

// RawDataGT applies the GT predicate on the "raw_data" field.
func RawDataGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldRawData, v))
}

// RawDataGTE applies the GTE predicate on the "raw_data" field.
func RawDataGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldRawData, v))
}

// RawDataLT applies the LT predicate on the "raw_data" field.
func RawDataLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldRawData, v))
}

// RawDataLTE applies the LTE predicate on the "raw_data" field.
func RawDataLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldRawData, v))
}

// RawDataContains applies the Contains predicate on the "raw_data" field.
func RawDataContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldRawData, v))
}

// RawDataHasPrefix applies the HasPrefix predicate on the "raw_data" field.
func RawDataHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldRawData, v))
}

// RawDataHasSuffix applies the HasSuffix predicate on the "raw_data" field.
func RawDataHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldRawData, v))
}

// RawDataIsNil applies the IsNil predicate on the "raw_data" field.
func RawDataIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldRawData))
}

// RawDataNotNil applies the NotNil predicate on the "raw_data" field.
func RawDataNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldRawData))
}

// RawDataEqualFold applies the EqualFold predicate on the "raw_data" field.
func RawDataEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldRawData, v))
}

// RawDataContainsFold applies the ContainsFold predicate on the "raw_data" field.
func RawDataContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldRawData, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Event) predicate.Event {
	return predicate.Event(sql.NotPredicates(p))
}
