// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "class_uid", Type: field.TypeInt},
		{Name: "category_uid", Type: field.TypeInt},
		{Name: "activity_id", Type: field.TypeInt},
		{Name: "type_uid", Type: field.TypeInt},
		{Name: "severity_id", Type: field.TypeInt, Nullable: true},
		{Name: "status_id", Type: field.TypeInt, Nullable: true},
		{Name: "time", Type: field.TypeInt64},
		{Name: "ingested_at", Type: field.TypeTime},
		{Name: "source", Type: field.TypeString, Default: "unknown"},
		{Name: "schema_version", Type: field.TypeString, Default: "1.3.0"},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "raw_data", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "event_class_uid_time",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[1], EventsColumns[7]},
			},
			{
				Name:    "event_category_uid_time",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[2], EventsColumns[7]},
			},
			{
				Name:    "event_type_uid_time",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[4], EventsColumns[7]},
			},
			{
				Name:    "event_source_time",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[9], EventsColumns[7]},
			},
			{
				Name:    "event_severity_id",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[5]},
			},
			{
				Name:    "event_status_id",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[6]},
			},
			{
				Name:    "event_time",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[7]},
			},
			{
				Name:    "event_ingested_at",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
	}
)

func init() {
}
