// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/ocsf-lake/ent/event"
)

// Event is the model entity for the Event schema.
type Event struct {
	config `json:"-"`
	// ID of the ent.
	// Unique storage identifier for the event
	ID string `json:"id,omitempty"`
	// OCSF event class identifier
	ClassUID int `json:"class_uid,omitempty"`
	// OCSF event category identifier
	CategoryUID int `json:"category_uid,omitempty"`
	// OCSF activity identifier
	ActivityID int `json:"activity_id,omitempty"`
	// OCSF event type identifier (class_uid * 100 + activity_id)
	TypeUID int `json:"type_uid,omitempty"`
	// OCSF severity level
	SeverityID int `json:"severity_id,omitempty"`
	// OCSF event status
	StatusID int `json:"status_id,omitempty"`
	// OCSF event time in epoch milliseconds
	Time int64 `json:"time,omitempty"`
	// Timestamp when the event was ingested into the lake
	IngestedAt time.Time `json:"ingested_at,omitempty"`
	// Source system that produced the event (e.g., 'aws-cloudtrail')
	Source string `json:"source,omitempty"`
	// OCSF schema version used for this event
	SchemaVersion string `json:"schema_version,omitempty"`
	// Full OCSF event payload as JSON
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Original raw event data before OCSF transformation
	RawData      string `json:"raw_data,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Event) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case event.FieldPayload:
			values[i] = new([]byte)
		case event.FieldClassUID, event.FieldCategoryUID, event.FieldActivityID, event.FieldTypeUID, event.FieldSeverityID, event.FieldStatusID, event.FieldTime:
			values[i] = new(sql.NullInt64)
		case event.FieldID, event.FieldSource, event.FieldSchemaVersion, event.FieldRawData:
			values[i] = new(sql.NullString)
		case event.FieldIngestedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Event fields.
func (_m *Event) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case event.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case event.FieldClassUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field class_uid", values[i])
			} else if value.Valid {
				_m.ClassUID = int(value.Int64)
			}
		case event.FieldCategoryUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field category_uid", values[i])
			} else if value.Valid {
				_m.CategoryUID = int(value.Int64)
			}
		case event.FieldActivityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field activity_id", values[i])
			} else if value.Valid {
				_m.ActivityID = int(value.Int64)
			}
		case event.FieldTypeUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type_uid", values[i])
			} else if value.Valid {
				_m.TypeUID = int(value.Int64)
			}
		case event.FieldSeverityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field severity_id", values[i])
			} else if value.Valid {
				_m.SeverityID = int(value.Int64)
			}
		case event.FieldStatusID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_id", values[i])
			} else if value.Valid {
				_m.StatusID = int(value.Int64)
			}
		case event.FieldTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				_m.Time = value.Int64
			}
		case event.FieldIngestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ingested_at", values[i])
			} else if value.Valid {
				_m.IngestedAt = value.Time
			}
		case event.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case event.FieldSchemaVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field schema_version", values[i])
			} else if value.Valid {
				_m.SchemaVersion = value.String
			}
		case event.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case event.FieldRawData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_data", values[i])
			} else if value.Valid {
				_m.RawData = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Event.
// This includes values selected through modifiers, order, etc.
func (_m *Event) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Event.
// Note that you need to call Event.Unwrap() before calling this method if this Event
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Event) Update() *EventUpdateOne {
	return NewEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Event entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Event) Unwrap() *Event {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Event is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Event) String() string {
	var builder strings.Builder
	builder.WriteString("Event(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("class_uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClassUID))
	builder.WriteString(", ")
	builder.WriteString("category_uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.CategoryUID))
	builder.WriteString(", ")
	builder.WriteString("activity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActivityID))
	builder.WriteString(", ")
	builder.WriteString("type_uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.TypeUID))
	builder.WriteString(", ")
	builder.WriteString("severity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SeverityID))
	builder.WriteString(", ")
	builder.WriteString("status_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusID))
	builder.WriteString(", ")
	builder.WriteString("time=")
	builder.WriteString(fmt.Sprintf("%v", _m.Time))
	builder.WriteString(", ")
	builder.WriteString("ingested_at=")
	builder.WriteString(_m.IngestedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("schema_version=")
	builder.WriteString(_m.SchemaVersion)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("raw_data=")
	builder.WriteString(_m.RawData)
	builder.WriteByte(')')
	return builder.String()
}

// Events is a parsable slice of Event.
type Events []*Event
