// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/ocsf-lake/ent/event"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
}

// SetClassUID sets the "class_uid" field.
func (_c *EventCreate) SetClassUID(v int) *EventCreate {
	_c.mutation.SetClassUID(v)
	return _c
}

// SetCategoryUID sets the "category_uid" field.
func (_c *EventCreate) SetCategoryUID(v int) *EventCreate {
	_c.mutation.SetCategoryUID(v)
	return _c
}

// SetActivityID sets the "activity_id" field.
func (_c *EventCreate) SetActivityID(v int) *EventCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetTypeUID sets the "type_uid" field.
func (_c *EventCreate) SetTypeUID(v int) *EventCreate {
	_c.mutation.SetTypeUID(v)
	return _c
}

// SetSeverityID sets the "severity_id" field.
func (_c *EventCreate) SetSeverityID(v int) *EventCreate {
	_c.mutation.SetSeverityID(v)
	return _c
}

// SetNillableSeverityID sets the "severity_id" field if the given value is not nil.
func (_c *EventCreate) SetNillableSeverityID(v *int) *EventCreate {
	if v != nil {
		_c.SetSeverityID(*v)
	}
	return _c
}

// SetStatusID sets the "status_id" field.
func (_c *EventCreate) SetStatusID(v int) *EventCreate {
	_c.mutation.SetStatusID(v)
	return _c
}

// SetNillableStatusID sets the "status_id" field if the given value is not nil.
func (_c *EventCreate) SetNillableStatusID(v *int) *EventCreate {
	if v != nil {
		_c.SetStatusID(*v)
	}
	return _c
}

// SetTime sets the "time" field.
func (_c *EventCreate) SetTime(v int64) *EventCreate {
	_c.mutation.SetTime(v)
	return _c
}

// SetIngestedAt sets the "ingested_at" field.
func (_c *EventCreate) SetIngestedAt(v time.Time) *EventCreate {
	_c.mutation.SetIngestedAt(v)
	return _c
}

// SetNillableIngestedAt sets the "ingested_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableIngestedAt(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetIngestedAt(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *EventCreate) SetSource(v string) *EventCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *EventCreate) SetNillableSource(v *string) *EventCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSchemaVersion sets the "schema_version" field.
func (_c *EventCreate) SetSchemaVersion(v string) *EventCreate {
	_c.mutation.SetSchemaVersion(v)
	return _c
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_c *EventCreate) SetNillableSchemaVersion(v *string) *EventCreate {
	if v != nil {
		_c.SetSchemaVersion(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *EventCreate) SetPayload(v map[string]interface{}) *EventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetRawData sets the "raw_data" field.
func (_c *EventCreate) SetRawData(v string) *EventCreate {
	_c.mutation.SetRawData(v)
	return _c
}

// SetNillableRawData sets the "raw_data" field if the given value is not nil.
func (_c *EventCreate) SetNillableRawData(v *string) *EventCreate {
	if v != nil {
		_c.SetRawData(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EventCreate) SetID(v string) *EventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the EventMutation object of the builder.
func (_c *EventCreate) Mutation() *EventMutation {
	return _c.mutation
}

// Save creates the Event in the database.
func (_c *EventCreate) Save(ctx context.Context) (*Event, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventCreate) defaults() {
	if _, ok := _c.mutation.IngestedAt(); !ok {
		v := event.DefaultIngestedAt()
		_c.mutation.SetIngestedAt(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := event.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		v := event.DefaultSchemaVersion
		_c.mutation.SetSchemaVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventCreate) check() error {
	if _, ok := _c.mutation.ClassUID(); !ok {
		return &ValidationError{Name: "class_uid", err: errors.New(`ent: missing required field "Event.class_uid"`)}
	}
	if v, ok := _c.mutation.ClassUID(); ok {
		if err := event.ClassUIDValidator(v); err != nil {
			return &ValidationError{Name: "class_uid", err: fmt.Errorf(`ent: validator failed for field "Event.class_uid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CategoryUID(); !ok {
		return &ValidationError{Name: "category_uid", err: errors.New(`ent: missing required field "Event.category_uid"`)}
	}
	if v, ok := _c.mutation.CategoryUID(); ok {
		if err := event.CategoryUIDValidator(v); err != nil {
			return &ValidationError{Name: "category_uid", err: fmt.Errorf(`ent: validator failed for field "Event.category_uid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "Event.activity_id"`)}
	}
	if v, ok := _c.mutation.ActivityID(); ok {
		if err := event.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "Event.activity_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TypeUID(); !ok {
		return &ValidationError{Name: "type_uid", err: errors.New(`ent: missing required field "Event.type_uid"`)}
	}
	if v, ok := _c.mutation.TypeUID(); ok {
		if err := event.TypeUIDValidator(v); err != nil {
			return &ValidationError{Name: "type_uid", err: fmt.Errorf(`ent: validator failed for field "Event.type_uid": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SeverityID(); ok {
		if err := event.SeverityIDValidator(v); err != nil {
			return &ValidationError{Name: "severity_id", err: fmt.Errorf(`ent: validator failed for field "Event.severity_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.StatusID(); ok {
		if err := event.StatusIDValidator(v); err != nil {
			return &ValidationError{Name: "status_id", err: fmt.Errorf(`ent: validator failed for field "Event.status_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Time(); !ok {
		return &ValidationError{Name: "time", err: errors.New(`ent: missing required field "Event.time"`)}
	}
	if _, ok := _c.mutation.IngestedAt(); !ok {
		return &ValidationError{Name: "ingested_at", err: errors.New(`ent: missing required field "Event.ingested_at"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Event.source"`)}
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		return &ValidationError{Name: "schema_version", err: errors.New(`ent: missing required field "Event.schema_version"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "Event.payload"`)}
	}
	return nil
}

func (_c *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Event.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ClassUID(); ok {
		_spec.SetField(event.FieldClassUID, field.TypeInt, value)
		_node.ClassUID = value
	}
	if value, ok := _c.mutation.CategoryUID(); ok {
		_spec.SetField(event.FieldCategoryUID, field.TypeInt, value)
		_node.CategoryUID = value
	}
	if value, ok := _c.mutation.ActivityID(); ok {
		_spec.SetField(event.FieldActivityID, field.TypeInt, value)
		_node.ActivityID = value
	}
	if value, ok := _c.mutation.TypeUID(); ok {
		_spec.SetField(event.FieldTypeUID, field.TypeInt, value)
		_node.TypeUID = value
	}
	if value, ok := _c.mutation.SeverityID(); ok {
		_spec.SetField(event.FieldSeverityID, field.TypeInt, value)
		_node.SeverityID = value
	}
	if value, ok := _c.mutation.StatusID(); ok {
		_spec.SetField(event.FieldStatusID, field.TypeInt, value)
		_node.StatusID = value
	}
	if value, ok := _c.mutation.Time(); ok {
		_spec.SetField(event.FieldTime, field.TypeInt64, value)
		_node.Time = value
	}
	if value, ok := _c.mutation.IngestedAt(); ok {
		_spec.SetField(event.FieldIngestedAt, field.TypeTime, value)
		_node.IngestedAt = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(event.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SchemaVersion(); ok {
		_spec.SetField(event.FieldSchemaVersion, field.TypeString, value)
		_node.SchemaVersion = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(event.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.RawData(); ok {
		_spec.SetField(event.FieldRawData, field.TypeString, value)
		_node.RawData = value
	}
	return _node, _spec
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
}

// Save creates the Event entities in the database.
func (_c *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Event, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
