// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/ocsf-lake/ent/event"
	"github.com/grokify/ocsf-lake/ent/predicate"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClassUID sets the "class_uid" field.
func (_u *EventUpdate) SetClassUID(v int) *EventUpdate {
	_u.mutation.ResetClassUID()
	_u.mutation.SetClassUID(v)
	return _u
}

// SetNillableClassUID sets the "class_uid" field if the given value is not nil.
func (_u *EventUpdate) SetNillableClassUID(v *int) *EventUpdate {
	if v != nil {
		_u.SetClassUID(*v)
	}
	return _u
}

// AddClassUID adds value to the "class_uid" field.
func (_u *EventUpdate) AddClassUID(v int) *EventUpdate {
	_u.mutation.AddClassUID(v)
	return _u
}

// SetCategoryUID sets the "category_uid" field.
func (_u *EventUpdate) SetCategoryUID(v int) *EventUpdate {
	_u.mutation.ResetCategoryUID()
	_u.mutation.SetCategoryUID(v)
	return _u
}

// SetNillableCategoryUID sets the "category_uid" field if the given value is not nil.
func (_u *EventUpdate) SetNillableCategoryUID(v *int) *EventUpdate {
	if v != nil {
		_u.SetCategoryUID(*v)
	}
	return _u
}

// AddCategoryUID adds value to the "category_uid" field.
func (_u *EventUpdate) AddCategoryUID(v int) *EventUpdate {
	_u.mutation.AddCategoryUID(v)
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *EventUpdate) SetActivityID(v int) *EventUpdate {
	_u.mutation.ResetActivityID()
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableActivityID(v *int) *EventUpdate {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// AddActivityID adds value to the "activity_id" field.
func (_u *EventUpdate) AddActivityID(v int) *EventUpdate {
	_u.mutation.AddActivityID(v)
	return _u
}

// SetTypeUID sets the "type_uid" field.
func (_u *EventUpdate) SetTypeUID(v int) *EventUpdate {
	_u.mutation.ResetTypeUID()
	_u.mutation.SetTypeUID(v)
	return _u
}

// SetNillableTypeUID sets the "type_uid" field if the given value is not nil.
func (_u *EventUpdate) SetNillableTypeUID(v *int) *EventUpdate {
	if v != nil {
		_u.SetTypeUID(*v)
	}
	return _u
}

// AddTypeUID adds value to the "type_uid" field.
func (_u *EventUpdate) AddTypeUID(v int) *EventUpdate {
	_u.mutation.AddTypeUID(v)
	return _u
}

// SetSeverityID sets the "severity_id" field.
func (_u *EventUpdate) SetSeverityID(v int) *EventUpdate {
	_u.mutation.ResetSeverityID()
	_u.mutation.SetSeverityID(v)
	return _u
}

// SetNillableSeverityID sets the "severity_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSeverityID(v *int) *EventUpdate {
	if v != nil {
		_u.SetSeverityID(*v)
	}
	return _u
}

// AddSeverityID adds value to the "severity_id" field.
func (_u *EventUpdate) AddSeverityID(v int) *EventUpdate {
	_u.mutation.AddSeverityID(v)
	return _u
}

// ClearSeverityID clears the value of the "severity_id" field.
func (_u *EventUpdate) ClearSeverityID() *EventUpdate {
	_u.mutation.ClearSeverityID()
	return _u
}

// SetStatusID sets the "status_id" field.
func (_u *EventUpdate) SetStatusID(v int) *EventUpdate {
	_u.mutation.ResetStatusID()
	_u.mutation.SetStatusID(v)
	return _u
}

// SetNillableStatusID sets the "status_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableStatusID(v *int) *EventUpdate {
	if v != nil {
		_u.SetStatusID(*v)
	}
	return _u
}

// AddStatusID adds value to the "status_id" field.
func (_u *EventUpdate) AddStatusID(v int) *EventUpdate {
	_u.mutation.AddStatusID(v)
	return _u
}

// ClearStatusID clears the value of the "status_id" field.
func (_u *EventUpdate) ClearStatusID() *EventUpdate {
	_u.mutation.ClearStatusID()
	return _u
}

// SetTime sets the "time" field.
func (_u *EventUpdate) SetTime(v int64) *EventUpdate {
	_u.mutation.ResetTime()
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *EventUpdate) SetNillableTime(v *int64) *EventUpdate {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// AddTime adds value to the "time" field.
func (_u *EventUpdate) AddTime(v int64) *EventUpdate {
	_u.mutation.AddTime(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *EventUpdate) SetSource(v string) *EventUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSource(v *string) *EventUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSchemaVersion sets the "schema_version" field.
func (_u *EventUpdate) SetSchemaVersion(v string) *EventUpdate {
	_u.mutation.SetSchemaVersion(v)
	return _u
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_u *EventUpdate) SetNillableSchemaVersion(v *string) *EventUpdate {
	if v != nil {
		_u.SetSchemaVersion(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *EventUpdate) SetPayload(v map[string]interface{}) *EventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetRawData sets the "raw_data" field.
func (_u *EventUpdate) SetRawData(v string) *EventUpdate {
	_u.mutation.SetRawData(v)
	return _u
}

// SetNillableRawData sets the "raw_data" field if the given value is not nil.
func (_u *EventUpdate) SetNillableRawData(v *string) *EventUpdate {
	if v != nil {
		_u.SetRawData(*v)
	}
	return _u
}

// ClearRawData clears the value of the "raw_data" field.
func (_u *EventUpdate) ClearRawData() *EventUpdate {
	_u.mutation.ClearRawData()
	return _u
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdate) Mutation() *EventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdate) check() error {
	if v, ok := _u.mutation.ClassUID(); ok {
		if err := event.ClassUIDValidator(v); err != nil {
			return &ValidationError{Name: "class_uid", err: fmt.Errorf(`ent: validator failed for field "Event.class_uid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CategoryUID(); ok {
		if err := event.CategoryUIDValidator(v); err != nil {
			return &ValidationError{Name: "category_uid", err: fmt.Errorf(`ent: validator failed for field "Event.category_uid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActivityID(); ok {
		if err := event.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "Event.activity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TypeUID(); ok {
		if err := event.TypeUIDValidator(v); err != nil {
			return &ValidationError{Name: "type_uid", err: fmt.Errorf(`ent: validator failed for field "Event.type_uid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SeverityID(); ok {
		if err := event.SeverityIDValidator(v); err != nil {
			return &ValidationError{Name: "severity_id", err: fmt.Errorf(`ent: validator failed for field "Event.severity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusID(); ok {
		if err := event.StatusIDValidator(v); err != nil {
			return &ValidationError{Name: "status_id", err: fmt.Errorf(`ent: validator failed for field "Event.status_id": %w`, err)}
		}
	}
	return nil
}

func (_u *EventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClassUID(); ok {
		_spec.SetField(event.FieldClassUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClassUID(); ok {
		_spec.AddField(event.FieldClassUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CategoryUID(); ok {
		_spec.SetField(event.FieldCategoryUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCategoryUID(); ok {
		_spec.AddField(event.FieldCategoryUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActivityID(); ok {
		_spec.SetField(event.FieldActivityID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActivityID(); ok {
		_spec.AddField(event.FieldActivityID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TypeUID(); ok {
		_spec.SetField(event.FieldTypeUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTypeUID(); ok {
		_spec.AddField(event.FieldTypeUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SeverityID(); ok {
		_spec.SetField(event.FieldSeverityID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeverityID(); ok {
		_spec.AddField(event.FieldSeverityID, field.TypeInt, value)
	}
	if _u.mutation.SeverityIDCleared() {
		_spec.ClearField(event.FieldSeverityID, field.TypeInt)
	}
	if value, ok := _u.mutation.StatusID(); ok {
		_spec.SetField(event.FieldStatusID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusID(); ok {
		_spec.AddField(event.FieldStatusID, field.TypeInt, value)
	}
	if _u.mutation.StatusIDCleared() {
		_spec.ClearField(event.FieldStatusID, field.TypeInt)
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(event.FieldTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTime(); ok {
		_spec.AddField(event.FieldTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(event.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SchemaVersion(); ok {
		_spec.SetField(event.FieldSchemaVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(event.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RawData(); ok {
		_spec.SetField(event.FieldRawData, field.TypeString, value)
	}
	if _u.mutation.RawDataCleared() {
		_spec.ClearField(event.FieldRawData, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetClassUID sets the "class_uid" field.
func (_u *EventUpdateOne) SetClassUID(v int) *EventUpdateOne {
	_u.mutation.ResetClassUID()
	_u.mutation.SetClassUID(v)
	return _u
}

// SetNillableClassUID sets the "class_uid" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableClassUID(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetClassUID(*v)
	}
	return _u
}

// AddClassUID adds value to the "class_uid" field.
func (_u *EventUpdateOne) AddClassUID(v int) *EventUpdateOne {
	_u.mutation.AddClassUID(v)
	return _u
}

// SetCategoryUID sets the "category_uid" field.
func (_u *EventUpdateOne) SetCategoryUID(v int) *EventUpdateOne {
	_u.mutation.ResetCategoryUID()
	_u.mutation.SetCategoryUID(v)
	return _u
}

// SetNillableCategoryUID sets the "category_uid" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableCategoryUID(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetCategoryUID(*v)
	}
	return _u
}

// AddCategoryUID adds value to the "category_uid" field.
func (_u *EventUpdateOne) AddCategoryUID(v int) *EventUpdateOne {
	_u.mutation.AddCategoryUID(v)
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *EventUpdateOne) SetActivityID(v int) *EventUpdateOne {
	_u.mutation.ResetActivityID()
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableActivityID(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// AddActivityID adds value to the "activity_id" field.
func (_u *EventUpdateOne) AddActivityID(v int) *EventUpdateOne {
	_u.mutation.AddActivityID(v)
	return _u
}

// SetTypeUID sets the "type_uid" field.
func (_u *EventUpdateOne) SetTypeUID(v int) *EventUpdateOne {
	_u.mutation.ResetTypeUID()
	_u.mutation.SetTypeUID(v)
	return _u
}

// SetNillableTypeUID sets the "type_uid" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableTypeUID(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetTypeUID(*v)
	}
	return _u
}

// AddTypeUID adds value to the "type_uid" field.
func (_u *EventUpdateOne) AddTypeUID(v int) *EventUpdateOne {
	_u.mutation.AddTypeUID(v)
	return _u
}

// SetSeverityID sets the "severity_id" field.
func (_u *EventUpdateOne) SetSeverityID(v int) *EventUpdateOne {
	_u.mutation.ResetSeverityID()
	_u.mutation.SetSeverityID(v)
	return _u
}

// SetNillableSeverityID sets the "severity_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSeverityID(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetSeverityID(*v)
	}
	return _u
}

// AddSeverityID adds value to the "severity_id" field.
func (_u *EventUpdateOne) AddSeverityID(v int) *EventUpdateOne {
	_u.mutation.AddSeverityID(v)
	return _u
}

// ClearSeverityID clears the value of the "severity_id" field.
func (_u *EventUpdateOne) ClearSeverityID() *EventUpdateOne {
	_u.mutation.ClearSeverityID()
	return _u
}

// SetStatusID sets the "status_id" field.
func (_u *EventUpdateOne) SetStatusID(v int) *EventUpdateOne {
	_u.mutation.ResetStatusID()
	_u.mutation.SetStatusID(v)
	return _u
}

// SetNillableStatusID sets the "status_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableStatusID(v *int) *EventUpdateOne {
	if v != nil {
		_u.SetStatusID(*v)
	}
	return _u
}

// AddStatusID adds value to the "status_id" field.
func (_u *EventUpdateOne) AddStatusID(v int) *EventUpdateOne {
	_u.mutation.AddStatusID(v)
	return _u
}

// ClearStatusID clears the value of the "status_id" field.
func (_u *EventUpdateOne) ClearStatusID() *EventUpdateOne {
	_u.mutation.ClearStatusID()
	return _u
}

// SetTime sets the "time" field.
func (_u *EventUpdateOne) SetTime(v int64) *EventUpdateOne {
	_u.mutation.ResetTime()
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableTime(v *int64) *EventUpdateOne {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// AddTime adds value to the "time" field.
func (_u *EventUpdateOne) AddTime(v int64) *EventUpdateOne {
	_u.mutation.AddTime(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *EventUpdateOne) SetSource(v string) *EventUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSource(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSchemaVersion sets the "schema_version" field.
func (_u *EventUpdateOne) SetSchemaVersion(v string) *EventUpdateOne {
	_u.mutation.SetSchemaVersion(v)
	return _u
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableSchemaVersion(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetSchemaVersion(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *EventUpdateOne) SetPayload(v map[string]interface{}) *EventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetRawData sets the "raw_data" field.
func (_u *EventUpdateOne) SetRawData(v string) *EventUpdateOne {
	_u.mutation.SetRawData(v)
	return _u
}

// SetNillableRawData sets the "raw_data" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableRawData(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetRawData(*v)
	}
	return _u
}

// ClearRawData clears the value of the "raw_data" field.
func (_u *EventUpdateOne) ClearRawData() *EventUpdateOne {
	_u.mutation.ClearRawData()
	return _u
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdateOne) Mutation() *EventMutation {
	return _u.mutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Event entity.
func (_u *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdateOne) check() error {
	if v, ok := _u.mutation.ClassUID(); ok {
		if err := event.ClassUIDValidator(v); err != nil {
			return &ValidationError{Name: "class_uid", err: fmt.Errorf(`ent: validator failed for field "Event.class_uid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CategoryUID(); ok {
		if err := event.CategoryUIDValidator(v); err != nil {
			return &ValidationError{Name: "category_uid", err: fmt.Errorf(`ent: validator failed for field "Event.category_uid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActivityID(); ok {
		if err := event.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "Event.activity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TypeUID(); ok {
		if err := event.TypeUIDValidator(v); err != nil {
			return &ValidationError{Name: "type_uid", err: fmt.Errorf(`ent: validator failed for field "Event.type_uid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SeverityID(); ok {
		if err := event.SeverityIDValidator(v); err != nil {
			return &ValidationError{Name: "severity_id", err: fmt.Errorf(`ent: validator failed for field "Event.severity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusID(); ok {
		if err := event.StatusIDValidator(v); err != nil {
			return &ValidationError{Name: "status_id", err: fmt.Errorf(`ent: validator failed for field "Event.status_id": %w`, err)}
		}
	}
	return nil
}

func (_u *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClassUID(); ok {
		_spec.SetField(event.FieldClassUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClassUID(); ok {
		_spec.AddField(event.FieldClassUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CategoryUID(); ok {
		_spec.SetField(event.FieldCategoryUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCategoryUID(); ok {
		_spec.AddField(event.FieldCategoryUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActivityID(); ok {
		_spec.SetField(event.FieldActivityID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActivityID(); ok {
		_spec.AddField(event.FieldActivityID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TypeUID(); ok {
		_spec.SetField(event.FieldTypeUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTypeUID(); ok {
		_spec.AddField(event.FieldTypeUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SeverityID(); ok {
		_spec.SetField(event.FieldSeverityID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeverityID(); ok {
		_spec.AddField(event.FieldSeverityID, field.TypeInt, value)
	}
	if _u.mutation.SeverityIDCleared() {
		_spec.ClearField(event.FieldSeverityID, field.TypeInt)
	}
	if value, ok := _u.mutation.StatusID(); ok {
		_spec.SetField(event.FieldStatusID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusID(); ok {
		_spec.AddField(event.FieldStatusID, field.TypeInt, value)
	}
	if _u.mutation.StatusIDCleared() {
		_spec.ClearField(event.FieldStatusID, field.TypeInt)
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(event.FieldTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTime(); ok {
		_spec.AddField(event.FieldTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(event.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SchemaVersion(); ok {
		_spec.SetField(event.FieldSchemaVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(event.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RawData(); ok {
		_spec.SetField(event.FieldRawData, field.TypeString, value)
	}
	if _u.mutation.RawDataCleared() {
		_spec.ClearField(event.FieldRawData, field.TypeString)
	}
	_node = &Event{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
