// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/ocsf-lake/ent/event"
	"github.com/grokify/ocsf-lake/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeEvent = "Event"
)

// EventMutation represents an operation that mutates the Event nodes in the graph.
type EventMutation struct {
	config
	op              Op
	typ             string
	id              *string
	class_uid       *int
	addclass_uid    *int
	category_uid    *int
	addcategory_uid *int
	activity_id     *int
	addactivity_id  *int
	type_uid        *int
	addtype_uid     *int
	severity_id     *int
	addseverity_id  *int
	status_id       *int
	addstatus_id    *int
	time            *int64
	addtime         *int64
	ingested_at     *time.Time
	source          *string
	schema_version  *string
	payload         *map[string]interface{}
	raw_data        *string
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*Event, error)
	predicates      []predicate.Event
}

var _ ent.Mutation = (*EventMutation)(nil)

// eventOption allows management of the mutation configuration using functional options.
type eventOption func(*EventMutation)

// newEventMutation creates new mutation for the Event entity.
func newEventMutation(c config, op Op, opts ...eventOption) *EventMutation {
	m := &EventMutation{
		config:        c,
		op:            op,
		typ:           TypeEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEventID sets the ID field of the mutation.
func withEventID(id string) eventOption {
	return func(m *EventMutation) {
		var (
			err   error
			once  sync.Once
			value *Event
		)
		m.oldValue = func(ctx context.Context) (*Event, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Event.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEvent sets the old Event of the mutation.
func withEvent(node *Event) eventOption {
	return func(m *EventMutation) {
		m.oldValue = func(context.Context) (*Event, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Event entities.
func (m *EventMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EventMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *EventMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Event.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetClassUID sets the "class_uid" field.
func (m *EventMutation) SetClassUID(i int) {
	m.class_uid = &i
	m.addclass_uid = nil
}

// ClassUID returns the value of the "class_uid" field in the mutation.
func (m *EventMutation) ClassUID() (r int, exists bool) {
	v := m.class_uid
	if v == nil {
		return
	}
	return *v, true
}

// OldClassUID returns the old "class_uid" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldClassUID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClassUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClassUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClassUID: %w", err)
	}
	return oldValue.ClassUID, nil
}

// AddClassUID adds i to the "class_uid" field.
func (m *EventMutation) AddClassUID(i int) {
	if m.addclass_uid != nil {
		*m.addclass_uid += i
	} else {
		m.addclass_uid = &i
	}
}

// AddedClassUID returns the value that was added to the "class_uid" field in this mutation.
func (m *EventMutation) AddedClassUID() (r int, exists bool) {
	v := m.addclass_uid
	if v == nil {
		return
	}
	return *v, true
}

// ResetClassUID resets all changes to the "class_uid" field.
func (m *EventMutation) ResetClassUID() {
	m.class_uid = nil
	m.addclass_uid = nil
}

// SetCategoryUID sets the "category_uid" field.
func (m *EventMutation) SetCategoryUID(i int) {
	m.category_uid = &i
	m.addcategory_uid = nil
}

// CategoryUID returns the value of the "category_uid" field in the mutation.
func (m *EventMutation) CategoryUID() (r int, exists bool) {
	v := m.category_uid
	if v == nil {
		return
	}
	return *v, true
}

// OldCategoryUID returns the old "category_uid" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldCategoryUID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCategoryUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCategoryUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCategoryUID: %w", err)
	}
	return oldValue.CategoryUID, nil
}

// AddCategoryUID adds i to the "category_uid" field.
func (m *EventMutation) AddCategoryUID(i int) {
	if m.addcategory_uid != nil {
		*m.addcategory_uid += i
	} else {
		m.addcategory_uid = &i
	}
}

// AddedCategoryUID returns the value that was added to the "category_uid" field in this mutation.
func (m *EventMutation) AddedCategoryUID() (r int, exists bool) {
	v := m.addcategory_uid
	if v == nil {
		return
	}
	return *v, true
}

// ResetCategoryUID resets all changes to the "category_uid" field.
func (m *EventMutation) ResetCategoryUID() {
	m.category_uid = nil
	m.addcategory_uid = nil
}

// SetActivityID sets the "activity_id" field.
func (m *EventMutation) SetActivityID(i int) {
	m.activity_id = &i
	m.addactivity_id = nil
}

// ActivityID returns the value of the "activity_id" field in the mutation.
func (m *EventMutation) ActivityID() (r int, exists bool) {
	v := m.activity_id
	if v == nil {
		return
	}
	return *v, true
}

// OldActivityID returns the old "activity_id" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldActivityID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActivityID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActivityID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActivityID: %w", err)
	}
	return oldValue.ActivityID, nil
}

// AddActivityID adds i to the "activity_id" field.
func (m *EventMutation) AddActivityID(i int) {
	if m.addactivity_id != nil {
		*m.addactivity_id += i
	} else {
		m.addactivity_id = &i
	}
}

// AddedActivityID returns the value that was added to the "activity_id" field in this mutation.
func (m *EventMutation) AddedActivityID() (r int, exists bool) {
	v := m.addactivity_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetActivityID resets all changes to the "activity_id" field.
func (m *EventMutation) ResetActivityID() {
	m.activity_id = nil
	m.addactivity_id = nil
}

// SetTypeUID sets the "type_uid" field.
func (m *EventMutation) SetTypeUID(i int) {
	m.type_uid = &i
	m.addtype_uid = nil
}

// TypeUID returns the value of the "type_uid" field in the mutation.
func (m *EventMutation) TypeUID() (r int, exists bool) {
	v := m.type_uid
	if v == nil {
		return
	}
	return *v, true
}

// OldTypeUID returns the old "type_uid" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldTypeUID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTypeUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTypeUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTypeUID: %w", err)
	}
	return oldValue.TypeUID, nil
}

// AddTypeUID adds i to the "type_uid" field.
func (m *EventMutation) AddTypeUID(i int) {
	if m.addtype_uid != nil {
		*m.addtype_uid += i
	} else {
		m.addtype_uid = &i
	}
}

// AddedTypeUID returns the value that was added to the "type_uid" field in this mutation.
func (m *EventMutation) AddedTypeUID() (r int, exists bool) {
	v := m.addtype_uid
	if v == nil {
		return
	}
	return *v, true
}

// ResetTypeUID resets all changes to the "type_uid" field.
func (m *EventMutation) ResetTypeUID() {
	m.type_uid = nil
	m.addtype_uid = nil
}

// SetSeverityID sets the "severity_id" field.
func (m *EventMutation) SetSeverityID(i int) {
	m.severity_id = &i
	m.addseverity_id = nil
}

// SeverityID returns the value of the "severity_id" field in the mutation.
func (m *EventMutation) SeverityID() (r int, exists bool) {
	v := m.severity_id
	if v == nil {
		return
	}
	return *v, true
}

// OldSeverityID returns the old "severity_id" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldSeverityID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeverityID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeverityID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeverityID: %w", err)
	}
	return oldValue.SeverityID, nil
}

// AddSeverityID adds i to the "severity_id" field.
func (m *EventMutation) AddSeverityID(i int) {
	if m.addseverity_id != nil {
		*m.addseverity_id += i
	} else {
		m.addseverity_id = &i
	}
}

// AddedSeverityID returns the value that was added to the "severity_id" field in this mutation.
func (m *EventMutation) AddedSeverityID() (r int, exists bool) {
	v := m.addseverity_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearSeverityID clears the value of the "severity_id" field.
func (m *EventMutation) ClearSeverityID() {
	m.severity_id = nil
	m.addseverity_id = nil
	m.clearedFields[event.FieldSeverityID] = struct{}{}
}

// SeverityIDCleared returns if the "severity_id" field was cleared in this mutation.
func (m *EventMutation) SeverityIDCleared() bool {
	_, ok := m.clearedFields[event.FieldSeverityID]
	return ok
}

// ResetSeverityID resets all changes to the "severity_id" field.
func (m *EventMutation) ResetSeverityID() {
	m.severity_id = nil
	m.addseverity_id = nil
	delete(m.clearedFields, event.FieldSeverityID)
}

// SetStatusID sets the "status_id" field.
func (m *EventMutation) SetStatusID(i int) {
	m.status_id = &i
	m.addstatus_id = nil
}

// StatusID returns the value of the "status_id" field in the mutation.
func (m *EventMutation) StatusID() (r int, exists bool) {
	v := m.status_id
	if v == nil {
		return
	}
	return *v, true
}

// OldStatusID returns the old "status_id" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldStatusID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatusID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatusID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatusID: %w", err)
	}
	return oldValue.StatusID, nil
}

// AddStatusID adds i to the "status_id" field.
func (m *EventMutation) AddStatusID(i int) {
	if m.addstatus_id != nil {
		*m.addstatus_id += i
	} else {
		m.addstatus_id = &i
	}
}

// AddedStatusID returns the value that was added to the "status_id" field in this mutation.
func (m *EventMutation) AddedStatusID() (r int, exists bool) {
	v := m.addstatus_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearStatusID clears the value of the "status_id" field.
func (m *EventMutation) ClearStatusID() {
	m.status_id = nil
	m.addstatus_id = nil
	m.clearedFields[event.FieldStatusID] = struct{}{}
}

// StatusIDCleared returns if the "status_id" field was cleared in this mutation.
func (m *EventMutation) StatusIDCleared() bool {
	_, ok := m.clearedFields[event.FieldStatusID]
	return ok
}

// ResetStatusID resets all changes to the "status_id" field.
func (m *EventMutation) ResetStatusID() {
	m.status_id = nil
	m.addstatus_id = nil
	delete(m.clearedFields, event.FieldStatusID)
}

// SetTime sets the "time" field.
func (m *EventMutation) SetTime(i int64) {
	m.time = &i
	m.addtime = nil
}

// Time returns the value of the "time" field in the mutation.
func (m *EventMutation) Time() (r int64, exists bool) {
	v := m.time
	if v == nil {
		return
	}
	return *v, true
}

// OldTime returns the old "time" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldTime(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTime: %w", err)
	}
	return oldValue.Time, nil
}

// AddTime adds i to the "time" field.
func (m *EventMutation) AddTime(i int64) {
	if m.addtime != nil {
		*m.addtime += i
	} else {
		m.addtime = &i
	}
}

// AddedTime returns the value that was added to the "time" field in this mutation.
func (m *EventMutation) AddedTime() (r int64, exists bool) {
	v := m.addtime
	if v == nil {
		return
	}
	return *v, true
}

// ResetTime resets all changes to the "time" field.
func (m *EventMutation) ResetTime() {
	m.time = nil
	m.addtime = nil
}

// SetIngestedAt sets the "ingested_at" field.
func (m *EventMutation) SetIngestedAt(t time.Time) {
	m.ingested_at = &t
}

// IngestedAt returns the value of the "ingested_at" field in the mutation.
func (m *EventMutation) IngestedAt() (r time.Time, exists bool) {
	v := m.ingested_at
	if v == nil {
		return
	}
	return *v, true
}

// OldIngestedAt returns the old "ingested_at" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldIngestedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIngestedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIngestedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIngestedAt: %w", err)
	}
	return oldValue.IngestedAt, nil
}

// ResetIngestedAt resets all changes to the "ingested_at" field.
func (m *EventMutation) ResetIngestedAt() {
	m.ingested_at = nil
}

// SetSource sets the "source" field.
func (m *EventMutation) SetSource(s string) {
	m.source = &s
}

// Source returns the value of the "source" field in the mutation.
func (m *EventMutation) Source() (r string, exists bool) {
	v := m.source
	if v == nil {
		return
	}
	return *v, true
}

// OldSource returns the old "source" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldSource(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSource is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSource requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSource: %w", err)
	}
	return oldValue.Source, nil
}

// ResetSource resets all changes to the "source" field.
func (m *EventMutation) ResetSource() {
	m.source = nil
}

// SetSchemaVersion sets the "schema_version" field.
func (m *EventMutation) SetSchemaVersion(s string) {
	m.schema_version = &s
}

// SchemaVersion returns the value of the "schema_version" field in the mutation.
func (m *EventMutation) SchemaVersion() (r string, exists bool) {
	v := m.schema_version
	if v == nil {
		return
	}
	return *v, true
}

// OldSchemaVersion returns the old "schema_version" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldSchemaVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSchemaVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSchemaVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSchemaVersion: %w", err)
	}
	return oldValue.SchemaVersion, nil
}

// ResetSchemaVersion resets all changes to the "schema_version" field.
func (m *EventMutation) ResetSchemaVersion() {
	m.schema_version = nil
}

// SetPayload sets the "payload" field.
func (m *EventMutation) SetPayload(value map[string]interface{}) {
	m.payload = &value
}

// Payload returns the value of the "payload" field in the mutation.
func (m *EventMutation) Payload() (r map[string]interface{}, exists bool) {
	v := m.payload
	if v == nil {
		return
	}
	return *v, true
}

// OldPayload returns the old "payload" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldPayload(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPayload is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPayload requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPayload: %w", err)
	}
	return oldValue.Payload, nil
}

// ResetPayload resets all changes to the "payload" field.
func (m *EventMutation) ResetPayload() {
	m.payload = nil
}

// SetRawData sets the "raw_data" field.
func (m *EventMutation) SetRawData(s string) {
	m.raw_data = &s
}

// RawData returns the value of the "raw_data" field in the mutation.
func (m *EventMutation) RawData() (r string, exists bool) {
	v := m.raw_data
	if v == nil {
		return
	}
	return *v, true
}

// OldRawData returns the old "raw_data" field's value of the Event entity.
// If the Event object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EventMutation) OldRawData(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRawData is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRawData requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRawData: %w", err)
	}
	return oldValue.RawData, nil
}

// ClearRawData clears the value of the "raw_data" field.
func (m *EventMutation) ClearRawData() {
	m.raw_data = nil
	m.clearedFields[event.FieldRawData] = struct{}{}
}

// RawDataCleared returns if the "raw_data" field was cleared in this mutation.
func (m *EventMutation) RawDataCleared() bool {
	_, ok := m.clearedFields[event.FieldRawData]
	return ok
}

// ResetRawData resets all changes to the "raw_data" field.
func (m *EventMutation) ResetRawData() {
	m.raw_data = nil
	delete(m.clearedFields, event.FieldRawData)
}

// Where appends a list predicates to the EventMutation builder.
func (m *EventMutation) Where(ps ...predicate.Event) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the EventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *EventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Event, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *EventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *EventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Event).
func (m *EventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EventMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.class_uid != nil {
		fields = append(fields, event.FieldClassUID)
	}
	if m.category_uid != nil {
		fields = append(fields, event.FieldCategoryUID)
	}
	if m.activity_id != nil {
		fields = append(fields, event.FieldActivityID)
	}
	if m.type_uid != nil {
		fields = append(fields, event.FieldTypeUID)
	}
	if m.severity_id != nil {
		fields = append(fields, event.FieldSeverityID)
	}
	if m.status_id != nil {
		fields = append(fields, event.FieldStatusID)
	}
	if m.time != nil {
		fields = append(fields, event.FieldTime)
	}
	if m.ingested_at != nil {
		fields = append(fields, event.FieldIngestedAt)
	}
	if m.source != nil {
		fields = append(fields, event.FieldSource)
	}
	if m.schema_version != nil {
		fields = append(fields, event.FieldSchemaVersion)
	}
	if m.payload != nil {
		fields = append(fields, event.FieldPayload)
	}
	if m.raw_data != nil {
		fields = append(fields, event.FieldRawData)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case event.FieldClassUID:
		return m.ClassUID()
	case event.FieldCategoryUID:
		return m.CategoryUID()
	case event.FieldActivityID:
		return m.ActivityID()
	case event.FieldTypeUID:
		return m.TypeUID()
	case event.FieldSeverityID:
		return m.SeverityID()
	case event.FieldStatusID:
		return m.StatusID()
	case event.FieldTime:
		return m.Time()
	case event.FieldIngestedAt:
		return m.IngestedAt()
	case event.FieldSource:
		return m.Source()
	case event.FieldSchemaVersion:
		return m.SchemaVersion()
	case event.FieldPayload:
		return m.Payload()
	case event.FieldRawData:
		return m.RawData()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case event.FieldClassUID:
		return m.OldClassUID(ctx)
	case event.FieldCategoryUID:
		return m.OldCategoryUID(ctx)
	case event.FieldActivityID:
		return m.OldActivityID(ctx)
	case event.FieldTypeUID:
		return m.OldTypeUID(ctx)
	case event.FieldSeverityID:
		return m.OldSeverityID(ctx)
	case event.FieldStatusID:
		return m.OldStatusID(ctx)
	case event.FieldTime:
		return m.OldTime(ctx)
	case event.FieldIngestedAt:
		return m.OldIngestedAt(ctx)
	case event.FieldSource:
		return m.OldSource(ctx)
	case event.FieldSchemaVersion:
		return m.OldSchemaVersion(ctx)
	case event.FieldPayload:
		return m.OldPayload(ctx)
	case event.FieldRawData:
		return m.OldRawData(ctx)
	}
	return nil, fmt.Errorf("unknown Event field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case event.FieldClassUID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClassUID(v)
		return nil
	case event.FieldCategoryUID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCategoryUID(v)
		return nil
	case event.FieldActivityID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActivityID(v)
		return nil
	case event.FieldTypeUID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTypeUID(v)
		return nil
	case event.FieldSeverityID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeverityID(v)
		return nil
	case event.FieldStatusID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatusID(v)
		return nil
	case event.FieldTime:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTime(v)
		return nil
	case event.FieldIngestedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIngestedAt(v)
		return nil
	case event.FieldSource:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSource(v)
		return nil
	case event.FieldSchemaVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSchemaVersion(v)
		return nil
	case event.FieldPayload:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPayload(v)
		return nil
	case event.FieldRawData:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRawData(v)
		return nil
	}
	return fmt.Errorf("unknown Event field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EventMutation) AddedFields() []string {
	var fields []string
	if m.addclass_uid != nil {
		fields = append(fields, event.FieldClassUID)
	}
	if m.addcategory_uid != nil {
		fields = append(fields, event.FieldCategoryUID)
	}
	if m.addactivity_id != nil {
		fields = append(fields, event.FieldActivityID)
	}
	if m.addtype_uid != nil {
		fields = append(fields, event.FieldTypeUID)
	}
	if m.addseverity_id != nil {
		fields = append(fields, event.FieldSeverityID)
	}
	if m.addstatus_id != nil {
		fields = append(fields, event.FieldStatusID)
	}
	if m.addtime != nil {
		fields = append(fields, event.FieldTime)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EventMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case event.FieldClassUID:
		return m.AddedClassUID()
	case event.FieldCategoryUID:
		return m.AddedCategoryUID()
	case event.FieldActivityID:
		return m.AddedActivityID()
	case event.FieldTypeUID:
		return m.AddedTypeUID()
	case event.FieldSeverityID:
		return m.AddedSeverityID()
	case event.FieldStatusID:
		return m.AddedStatusID()
	case event.FieldTime:
		return m.AddedTime()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EventMutation) AddField(name string, value ent.Value) error {
	switch name {
	case event.FieldClassUID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddClassUID(v)
		return nil
	case event.FieldCategoryUID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCategoryUID(v)
		return nil
	case event.FieldActivityID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddActivityID(v)
		return nil
	case event.FieldTypeUID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTypeUID(v)
		return nil
	case event.FieldSeverityID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSeverityID(v)
		return nil
	case event.FieldStatusID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatusID(v)
		return nil
	case event.FieldTime:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTime(v)
		return nil
	}
	return fmt.Errorf("unknown Event numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EventMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(event.FieldSeverityID) {
		fields = append(fields, event.FieldSeverityID)
	}
	if m.FieldCleared(event.FieldStatusID) {
		fields = append(fields, event.FieldStatusID)
	}
	if m.FieldCleared(event.FieldRawData) {
		fields = append(fields, event.FieldRawData)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EventMutation) ClearField(name string) error {
	switch name {
	case event.FieldSeverityID:
		m.ClearSeverityID()
		return nil
	case event.FieldStatusID:
		m.ClearStatusID()
		return nil
	case event.FieldRawData:
		m.ClearRawData()
		return nil
	}
	return fmt.Errorf("unknown Event nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EventMutation) ResetField(name string) error {
	switch name {
	case event.FieldClassUID:
		m.ResetClassUID()
		return nil
	case event.FieldCategoryUID:
		m.ResetCategoryUID()
		return nil
	case event.FieldActivityID:
		m.ResetActivityID()
		return nil
	case event.FieldTypeUID:
		m.ResetTypeUID()
		return nil
	case event.FieldSeverityID:
		m.ResetSeverityID()
		return nil
	case event.FieldStatusID:
		m.ResetStatusID()
		return nil
	case event.FieldTime:
		m.ResetTime()
		return nil
	case event.FieldIngestedAt:
		m.ResetIngestedAt()
		return nil
	case event.FieldSource:
		m.ResetSource()
		return nil
	case event.FieldSchemaVersion:
		m.ResetSchemaVersion()
		return nil
	case event.FieldPayload:
		m.ResetPayload()
		return nil
	case event.FieldRawData:
		m.ResetRawData()
		return nil
	}
	return fmt.Errorf("unknown Event field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EventMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EventMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EventMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EventMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Event unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EventMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Event edge %s", name)
}
