// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/grokify/ocsf-lake/ent/event"
	"github.com/grokify/ocsf-lake/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescClassUID is the schema descriptor for class_uid field.
	eventDescClassUID := eventFields[1].Descriptor()
	// event.ClassUIDValidator is a validator for the "class_uid" field. It is called by the builders before save.
	event.ClassUIDValidator = eventDescClassUID.Validators[0].(func(int) error)
	// eventDescCategoryUID is the schema descriptor for category_uid field.
	eventDescCategoryUID := eventFields[2].Descriptor()
	// event.CategoryUIDValidator is a validator for the "category_uid" field. It is called by the builders before save.
	event.CategoryUIDValidator = eventDescCategoryUID.Validators[0].(func(int) error)
	// eventDescActivityID is the schema descriptor for activity_id field.
	eventDescActivityID := eventFields[3].Descriptor()
	// event.ActivityIDValidator is a validator for the "activity_id" field. It is called by the builders before save.
	event.ActivityIDValidator = eventDescActivityID.Validators[0].(func(int) error)
	// eventDescTypeUID is the schema descriptor for type_uid field.
	eventDescTypeUID := eventFields[4].Descriptor()
	// event.TypeUIDValidator is a validator for the "type_uid" field. It is called by the builders before save.
	event.TypeUIDValidator = eventDescTypeUID.Validators[0].(func(int) error)
	// eventDescSeverityID is the schema descriptor for severity_id field.
	eventDescSeverityID := eventFields[5].Descriptor()
	// event.SeverityIDValidator is a validator for the "severity_id" field. It is called by the builders before save.
	event.SeverityIDValidator = eventDescSeverityID.Validators[0].(func(int) error)
	// eventDescStatusID is the schema descriptor for status_id field.
	eventDescStatusID := eventFields[6].Descriptor()
	// event.StatusIDValidator is a validator for the "status_id" field. It is called by the builders before save.
	event.StatusIDValidator = eventDescStatusID.Validators[0].(func(int) error)
	// eventDescIngestedAt is the schema descriptor for ingested_at field.
	eventDescIngestedAt := eventFields[8].Descriptor()
	// event.DefaultIngestedAt holds the default value on creation for the ingested_at field.
	event.DefaultIngestedAt = eventDescIngestedAt.Default.(func() time.Time)
	// eventDescSource is the schema descriptor for source field.
	eventDescSource := eventFields[9].Descriptor()
	// event.DefaultSource holds the default value on creation for the source field.
	event.DefaultSource = eventDescSource.Default.(string)
	// eventDescSchemaVersion is the schema descriptor for schema_version field.
	eventDescSchemaVersion := eventFields[10].Descriptor()
	// event.DefaultSchemaVersion holds the default value on creation for the schema_version field.
	event.DefaultSchemaVersion = eventDescSchemaVersion.Default.(string)
}
